- block:
    - name: Checking docker service
      service:
        name: docker
        state: started
      changed_when: false
  rescue:
    - name: Installing docker.io and docker-compose
      apt:
        name:
          - docker.io
          - docker-compose
    - name: Add my account to group 'docker'
      user:
        name: "{{ ansible_user_id }}"
        group: docker
        append: yes
    - name: Add kernel swap limit capabilities
      lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX="
        line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
    - name: Updating grub
      command: update-grub

- name: Updating docker daemon config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: Restart docker service
