- block:
    - name: Checking docker service
      service:
        name: docker
        state: started
      changed_when: false
  rescue:
    - name: Installing docker.io and docker-compose
      apt:
        name: "{{ item }}"
      with_items:
        - docker.io
        - docker-compose
    - name: Add my account to group 'docker'
      user:
        name: "{{ ansible_user_id }}"
        group: docker
        append: yes
