- name: "Create {{ ansible_user_dir }}/.ansible/tmp"
  file:
    path: "{{ ansible_user_dir }}/.ansible/tmp"
    state: directory
    mode: 0700

- include_tasks: hostname.yml

- include_tasks: resolv.yml

- include_tasks: tools.yml

- include_tasks: config.yml

# - include_tasks: apt_fast.yml
