- block:
    - name: Setup DNS servers | xenial
      lineinfile:
        path: "/etc/resolvconf/resolv.conf.d/head"
        line: "nameserver {{ item }}"
      with_items: "{{ dns_servers }}"
      register: resolvconf
    - name: Restarting resolvconf service
      service:
        name: resolvconf
        state: restarted
      when: resolvconf is changed
  when: ansible_distribution_release == 'xenial'

- block:
    - name: Setup DNS servers | bionic
      ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNS
        value: "{{ dns_servers | join(' ') }}"
      register: resolved
    - name: Restarting systemd-resolved service
      service:
        name: systemd-resolved
        state: restarted
      when: resolved is changed
  when: ansible_distribution_release == 'bionic'
